name: Deploy Lambda

on:
  push:
    branches:
      - main  # or specify your branch name

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Create Lambda function ZIP archive
        run: |
          zip -r lambda_function.zip .

      - name: Upload ZIP archive to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: lambda_function
          path: ./lambda_function.zip

      - name: Deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda update-function-code --function-name malaka_oshirish_version_2 --zip-file fileb://./lambda_function.zip
